# Generated by Django 5.1.2 on 2024-12-08 01:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('reverse', 'Reverse'), ('login', 'User Login'), ('logout', 'User Logout'), ('other', 'Other')], help_text='Type of action performed', max_length=50)),
                ('model_name', models.CharField(help_text='Name of the model affected', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the action')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
