# Generated by Django 5.1.2 on 2024-11-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product category (e.g., Dairy, Bakery, Beverages)', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the category', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the product (optional)', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the product price', max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Enter the available quantity of the product', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select a category for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the package name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the package (optional)', null=True)),
                ('package_price', models.DecimalField(decimal_places=2, help_text='Enter the price for the entire package', max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total quantity of the package available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove'), ('Sale', 'Sale')], help_text='Type of inventory change', max_length=50)),
                ('quantity_changed', models.PositiveIntegerField(help_text='Amount by which the quantity was changed')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the change', null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='product.product')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='product.productpackage')),
            ],
        ),
    ]
