# Generated by Django 5.1.2 on 2024-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productpackage_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the bulk cost  product price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the bulk selling product price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the cost  product price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the selling product price', max_digits=10, null=True),
        ),
    ]
