# Generated by Django 5.1.2 on 2024-12-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_price_product_bulk_cost_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bulk_price',
            new_name='bulk_selling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='unit_cost_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='unit_selling_price',
        ),
    ]
