# Generated by Django 5.1.2 on 2024-12-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_bulk_price_product_bulk_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select a category for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.productcategory'),
        ),
    ]
