# Generated by Django 5.1.2 on 2024-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_quantity_product_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_per_bulk',
            field=models.PositiveIntegerField(default=1, help_text='Enter the number of unit quantities that make up a bulk quantity', null=True),
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
    ]
