# Generated by Django 5.1.2 on 2024-12-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_units_per_bulk_delete_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bulk_cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the bulk cost product price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the cost product price', max_digits=10, null=True),
        ),
    ]
