# Generated by Django 5.1.2 on 2024-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_bulk_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_available_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Enter the available quantity of the product', null=True),
        ),
    ]
