# Generated by Django 5.1.2 on 2024-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.BooleanField(default=False, null=True)),
                ('always_print_receipt', models.BooleanField(default=False, null=True)),
                ('change_date_sale', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
