# Generated by Django 5.1.2 on 2024-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('add', 'Stock Added'), ('remove', 'Stock Removed'), ('sale', 'Product Sold')], help_text='The type of action (add, remove, adjust, sale)', max_length=10),
        ),
    ]
