# Generated by Django 5.1.2 on 2024-12-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_product_previous_available_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the sale was made')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the sale record was last updated')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue for the sale', max_digits=12)),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], help_text='Status of the sale', max_length=100, null=True)),
                ('cashier_name', models.CharField(blank=True, help_text="Cashier's name", max_length=255, null=True)),
                ('sale_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the product sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit selling price at the time of sale', max_digits=10)),
                ('product', models.ForeignKey(help_text='The associated product', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale', models.ForeignKey(help_text='The associated sale', on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(help_text='Products involved in this sale', related_name='sales', through='sales.SaleProduct', to='product.product'),
        ),
    ]
