# Generated by Django 5.1.2 on 2024-12-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='sale_type',
            field=models.CharField(choices=[('Unit', 'Unit'), ('Bulk', 'Bulk')], default='Unit', help_text='Type of the sale (Unit or Bulk)', max_length=10),
        ),
    ]
