# Generated by Django 5.1.2 on 2024-12-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleproduct_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
