# Generated by Django 5.1.2 on 2024-12-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_sale_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue for the sale', max_digits=40),
        ),
    ]
