# Generated by Django 5.1.2 on 2024-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_amount_paid_sale_balance_sale_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(help_text='Date and time when the sale was made'),
        ),
    ]
