# Generated by Django 5.1.2 on 2024-12-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price at the time of sale', max_digits=10),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount for this product in the sale', max_digits=15),
        ),
    ]
