# Generated by Django 5.1.2 on 2024-12-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleproduct_selling_price_saleproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='saleproduct',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='bulk_selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price  for bulk at the time of sale', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='bulk price at the time of sale', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit selling price at the time of sale', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='unit Selling price at the time of sale', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount for this product in the sale', max_digits=15, null=True),
        ),
    ]
