# Generated by Django 5.1.2 on 2024-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_saleproduct_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=40, null=True),
        ),
    ]
